In [0]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import torch

from pathlib import Path
HOME = Path.home()
MNIST_PATH = HOME / 'data' / 'mnist'

### Read this First

#### Remember that `tab` is is useful for autocompletion.

#### Remember that `shift + tab` is useful for rapidly obtaining usage + documentation.

### Basic Shapes and Types in NumPy

**Create a 1-D array of 5 zeros named `array_of_zeros`. Print it, verify that its shape is `[5]`, and print its `dtype`.**

**Print the transpose of `array_of_zeros`.**

**In the following Markdown Cell, answer:**

**Is its transpose what you expected? Why or why not?**

**Create a 2-D array of 5 zeros, named `array_of_zeros`, with shape `[1, 5]`. Print it, and print its shape.**

**Print the transpose of `array_of_zeros`.**

**In the following Markdown Cell, answer:**

**Is its transpose what you expected? Why or why not?**

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.float`. Print it, and its `dtype`.**

**In the following Markdown Cell, answer:**

**Does this array contain floats with 32 bit precision or 64 bit precision?**

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.int`. Print it, and its `dtype`.**

**In the following Markdown Cell, answer:**

**Does this array contain 32-bit integers or 64-bit integers?**

When dealing with GPUs, we will often want to use 32 bit precision.

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.float32`. Print it, and its `dtype`.**

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.float`, and then create `array_of_zeros_32` by casting `array_of_zeros`. Print it, and its `dtype`.**

### `np.arange`, Element-Wise Operations, and Reshaping

**Create `x1` to be a 1-D array of floats containing `[0, 1, 2, 3, 4]`, but do not type these values explicitly; instead, use `np.arange`. Also create `x2` in the exact same way. Print `x1`, `x2`, and `x1`'s `dtype`. Be sure `x1` and `x2` store floats, not ints.**

**Create `y` via `y = x1 + x2`. Print `y` and its `dtype`.**

**Reshape `x1` to have shape `[1, 5]` and `x2` to have shape `[5, 1]`. Print their shapes.**

**Form `y` via `y = x1 + x2`. Print `y`.**

**In the following Markdown Cell, answer:**

**Is this what you expected? (For now, just a 'Yes' or 'No' is fine; we will revisit this result later.)**

**Create a 1-D array x containing integers 0, 1, ..., 8 using `np.arange`. Print it, and its `dtype`.**

**Create `X` by reshaping `x` to have shape `[3, 3]`. Print `X`.**

NumPy arrays are typically contiguous strips of memory, with the shape specifying how we view that memory. For example, if the shape of the strip of memory `[0, 1, 2, 3]` is `[2, 2]`, then we view it as a 2 x 2 matrix.


**In the following Markdown Cell, answer:**


**Given your previous `reshape` result, and the fact that `reshape` only changes our view of a contiguous strip of memory, do *rows* have elements that are mutually closer in memory, or do *columns* have elements that are mutually closer in memory?**

### Indexing, Masks, and Concatenation Using MNIST

**Run the following code to download and load the MNIST training set.** (The data will be downloaded if it is not already present.)

In [0]:
import torchvision
official_mnist_train = torchvision.datasets.MNIST(str(MNIST_PATH), train=True, download=True)
train_images = official_mnist_train.train_data.numpy().astype(np.float)
train_labels = official_mnist_train.train_labels.numpy().astype(np.int)

**Print the shape of `train_images` and `train_labels`.**

**In the following Markdown Cell, answer:**

**Based on these shapes, how many training images are there? And what is the height and width of each image?**

**Form `first_image` as a 2-D array with shape `[28, 28]`, containing the 0-th image of `train_images`, and visualize `first_image` using `plt.imshow`.** Also feel free to run `plt.set_cmap('gray')` after plotting the image if you'd like to see it using a grayscale colormap.

**Print the label of the 0-th image.**

**Create a 2-D array `first_image_flipped` that consists of the first training image *but flipped horizontally*, and visualize the result using `plt.imshow`.** Note that `first_image` has a shape of `[H, W]`, where `H` is the height of the image and `W` is the width of the image.

**Create a 2-D array `first_image_down_2` that consists of the first training image but downsampled by a factor of 2, and plot the result using `plt.imshow`.** (The resulting image should have shape `[14, 14]`.)

**Create a 2-D array `first_image_down_4` that consists of the first training image but downsampled by a factor of 4, and plot the result using `plt.imshow`.** (The resulting image should have shape `[7, 7]`.)

**Print the minimum and maximum values of `first_image`.**

**Create a copy of `first_image`, `first_image_copy`, using `first_image_copy = first_image.copy()`.**

**Create a 2-D boolean mask named `mask` with the same shape as `first_image_copy`, with elements that are `True` whenever a pixel's value exceeds 50 and which is `False` otherwise. Print `mask`'s `dtype` and also print how many values are `True`.**

**Visualize `mask` using `plt.imshow`.**

**Create `mask_upper_half` by keeping only the upper half of `mask`, and visualize `mask_upper_half` using `plt.imshow`.** (`mask_upper_half` should have shape `[14, 28]`.)

**Halve all pixels that exceed 50 in `first_image_copy` that exceed a value of 50, in place, using `mask`, and then print the minimum and maximum values of `first_image_copy`.**

**Form `first_ten_images_as_one` by concatenating the first 10 training MNIST images horizontally, and visualize the result using `plt.imshow`.**

### Element-Wise Multiplication vs. Matrix Multiplication

**Create `A` and `B`, each 2-D matrices of ones with shape `[3, 3]`.**

**Form `C_star` via `C_star = A * B`, and print `C_star`.**

**Form `C_at` via `C_at = A @ B`, and print `C_at`.**

**In the following Markdown Cell, answer:**

**What operation does `*` perform? What operation does `@` perform?**

### Broadcasting

Suppose you have some data collected in a 1-D array, which is not 'normalized' in the sense that it has a mean that's far from 0 and a standard deviation that's far from 1:

In [0]:
x = np.array([3.2, 1.1, 1.2, 5.3, 3.9, 1.9, 2.0, 6.2, 1.0, 2.2])
print(x.mean())
print(x.std())

2.8
1.7227884373886422


**Form `z` by normalizing `x`. That is, each entry in `z` should be the *standardized score* of the corresponding entry in `x`: $z_i = (x_i - \mu) / \sigma$. Print `z` and verify that its mean is close to 0.0 and that its standard deviation is close to 1.0.**

Now suppose that you have 5 3-dimensional feature vectors collected in an array, and that none of the features are normalized, in that each feature has a mean that's far from 0 and a standard deviation that's far from 1:

In [0]:
data = np.array([[7.5, -1.1,  1.6],
                 [0.1,  0.9, -0.7],
                 [6.3, -0.9,  3.1],
                 [2.5, -0.6,  0.4],
                 [2.4, -0.1,  1.0]])
print(data.mean(axis=0))
print(data.std(axis=0))

[ 3.76 -0.36  1.08]
[2.73027471 0.71442284 1.26396202]


**Write code to normalize this data on a feature-wise basis, so that each feature has mean 0 and standard deviation 1, and store the result in `normalized_data`. Print `normalized_data` along with its per-feature mean and its per-feature standard deviation.**

Now suppose that you have 3 3-D vectors that each represent *unnormalized class scores*. That is, each 3-D vector represents the scores for three different classes in a classification problem. (For example, these could be the outputs of an image-classification model, with each row corresponding to a particular image and each column corresponding to a particular class, such as 'dog', 'cat', or 'other'.)

If each row represented a valid probability distribution, then their elements would sum do 1, but they currently do not:

In [0]:
scores = np.array([[8.2, 6.7, 6.3],
                   [9.5, 0.2, 9.3],
                   [3.6, 2.7, 9.0]])
print(scores)
print(scores.sum(axis=1))

[[8.2 6.7 6.3]
 [9.5 0.2 9.3]
 [3.6 2.7 9. ]]
[21.2 19.  15.3]


**Write code to compute and print the array `probabilities` by dividing each row of `scores` by its sum. Print `probabilities` and the sum of each of its rows, to verify that each row sums to 1.** Hint: If the rows do not sum to 1, then think about broadcasting and take a look at the `keepdims` keyword argument of NumPy's `sum` function.

**Complete the `tril_` function below by inserting only 2 lines of code at the bottom of the function.** Hint: Form a mask using broadcasting, and use the mask to modify `X` in place.

In [0]:
def tril_(X):
    """Modify X in place to become lower triangular.

    Args:
        X: A 2-D NumPy array with shape [M, N].
    """
    if X.ndim != 2:
        raise ValueError('X must be a 2-D array.')
    M, N = X.shape
    i = np.arange(M).reshape(1, M)
    j = np.arange(N).reshape(N, 1)
    
    # TODO: Replace with valid code.
    pass

**Create a random matrix `X` with shape `[3, 3]` using `np.random.rand`, run `tril_(X)`, and verify that `X` is now lower triangular.**

**Create a random matrix `X` with shape `[5, 5]` using `np.random.rand`, run `tril_(X)`, and verify that `X` is now lower triangular.**

### Booleans vs. Masks

**Create `x` using `x = np.array([1, 2, 3])`, and create `y` using `y = x`.**

**Print the expression `x == y`.**

**Use `np.all` to test whether *all* elements of `x` are equal to their corresponding elements in `y`. You should print the result, which should be a single boolean, `True` or `False`.**

**Modify the 0-th element of `y` via `y[0] = 5`, and again use `np.all` to test whether all elements of `x` are equal to their corresponding elements in `y`, and again print the result.**

**In the Markdown Cell below, answer:**

**Is the last result what you expected? Explain what is happening here.**

**Create `x = np.array([1, 2, 3])` and `y = np.array([2, 2, 2])`. Again use `np.all` to test whether all elements of `x` are equal to their corresponding elements in `y`, and again print the result.**

**Use `np.any` to test whether *any* elements of `x` are equal to their corresponding elements in `y`, and again print the result.**